---
title: 'Making next-generation PDFs with Quarto and `typst`'
subtitle: Never again in outer par mode
author: Carlos Scheidegger
format: 
  revealjs-positslides:
    filters:
      - positslides
    css: styles.css
---

## {}

````
---
title: my report is _so good_
format: pdf
---

::: {#tbl-1}

```{{r}}
#| tbl-cap: Look at this table. Look at it!
knitr::kable(my_dataframe)
```

:::

As you can see in @tbl-1, this is important!
````

## {}

```
$ quarto render index.qmd
```

## {}

```
$ quarto render index.qmd
...
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
```

## {}

```
$ quarto render index.qmd
...
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr
```

## {}

```
$ quarto render index.qmd
...
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
```

## {}

```
$ quarto render index.qmd
...
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
```

::: {.error-code-color}
```
ERROR:
compilation failed- error
```

::: {.error-code-bold}
``` 
LaTeX Error: Not in outer par mode.
```
:::

:::


## {}

```
$ quarto render index.qmd
...
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
ERROR:
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.690 \centering
see /Users/cscheid/Desktop/daily-log/2023/09/07/QmdReport/index.log for more information.
ERROR: Error
```

## {}

```
$ ls -l index.log
-rw-r--r--  1 cscheid  staff  50214 Sep  7 11:54 index.log
```

## {}

::: {.smaller}

```
$ ls -l index.log
-rw-r--r--  1 cscheid  staff  50214 Sep  7 11:54 index.log

$ cat /Users/cscheid/Desktop/daily-log/2023/09/07/QmdReport/index.log
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex 2023.9.6)  7 SEP 2023 11:54
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**index.tex
(./index.tex
LaTeX2e <2023-06-01> patch level 1
L3 programming layer <2023-08-29>
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrbook.cls
Document Class: scrbook 2023/07/07 v3.41 KOMA-Script document class (book)
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrkbase.sty
Package: scrkbase 2023/07/07 v3.41 KOMA-Script package (KOMA-Script-dependent basics and keyval usage)
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrbase.sty
Package: scrbase 2023/07/07 v3.41 KOMA-Script package (KOMA-Script-independent basics and keyval usage)
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrlfile.sty
Package: scrlfile 2023/07/07 v3.41 KOMA-Script package (file load hooks)
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
Package: scrlfile-hook 2023/07/07 v3.41 KOMA-Script package (using LaTeX hooks)
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrlogo.sty
Package: scrlogo 2023/07/07 v3.41 KOMA-Script package (logo)
))) (/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2022/05/29 v1.15 key=value parser (DPC)
\KV@toks@=\toks17
)
Applying: [2021/05/01] Usage of raw or classic option list on input line 252.
Already applied: [0000/00/00] Usage of raw or classic option list on input line 368.
)) (/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/tocbasic.sty
Package: tocbasic 2023/07/07 v3.41 KOMA-Script package (handling toc-files)
\scr@dte@tocline@numberwidth=\skip48
\scr@dte@tocline@numbox=\box51
)
Package tocbasic Info: omitting babel extension for `toc'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `toc' on input line 135.
Class scrbook Info: You've used standard option `oneside'.
(scrbook)           This is correct!
(scrbook)           Internally I'm using `twoside=false'.
(scrbook)           If you'd like to set the option with \KOMAoptions,
(scrbook)           you'd have to use `twoside=false' there
(scrbook)           instead of `oneside', too.
Class scrbook Info: File `scrsize11pt.clo' used instead of
(scrbook)           file `scrsize11.clo' to setup font sizes on input line 2691.
(/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/scrsize11pt.clo
File: scrsize11pt.clo 2023/07/07 v3.41 KOMA-Script font size class option (11pt)
) (/Users/cscheid/Library/TinyTeX/texmf-dist/tex/latex/koma-script/typearea.sty
Package: typearea 2023/07/07 v3.41 KOMA-Script package (type area)
\ta@bcor=\skip49
\ta@div=\count181
Package typearea Info: You've used standard option `letterpaper'.
(typearea)             This is correct!
```

:::

## {}

````
---
title: "seriously y'all, my report is _the best_"
format: pdf
---

```{{r}}
#| label: tbl-main_result
#| tbl-cap: Look at this table. Look at it!
knitr::kable(my_dataframe)
```

You need to see @tbl-main_result.
````

## {}

```
$ quarto render index.qmd
```

## {}

```
$ quarto render index.qmd
...
ERROR: 
compilation failed- error
```

## {}

```
$ quarto render index.qmd
...
ERROR: 
compilation failed- error
Missing \endcsname inserted.
```

## Ok, but what's Typst?

An entirely new language for writing documents.

You _could_ use that by itself, but Quarto!

Quarto 1.4 provides `typst` as a new output format.

## Why I'm excited about Typst

- Much, *much* better error messages

- No LaTeX dependencies to install

- Much easier to write extensions and new templates

# Error messages matter

Quarto calls downstream tools directly. When something fails, we either have to fix it ourselves by parsing the error message (mklatex etc) or we report the error.

We put a _lot_ of effort in producing good error messages, but there's only so much we can do.

# No LaTeX

## No `tinytex` required: quarto bundles `typst`

## Typst is fast!

One fairly annoying thing about Quarto is that it's kind of slow (acknowledge and mention 2023 speed fixes, as well as 2024). With PDF output from LaTeX, it's that much slower. But Typst is very fast! (Demo.)

# Extensions

## Cool things you can do with Quarto+Typst today

https://github.com/quarto-ext/typst-templates

## Do you want to write your own?

Two-slide demo.

Talk about error messages in writing extensions. 

Show Typst error messages.